name: update-emui-icons
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: mfinelli/setup-imagemagick@v1

      - name: Get ImageMagick version
        run: |
          convert -version

      - name: test for getting commit depth
        run: |
          event_path=$GITHUB_EVENT_PATH
          commit_count=$(jq -r '.commits | length' $event_path)
          echo "Push event contained $commit_count commits"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          path: $GITHUB_EVENT_PATH
