name: update-emui-icons
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: mfinelli/setup-imagemagick@v1

      - name: Get ImageMagick version
        run: |
          convert -version

      - name: Clone MIUI Icons
        run: |
          git clone https://github.com/pzcn/MIUI-Adapted-Icons-Complement-Project.git

      - name: Convert MIUI to EMUI
        run: |
          mkdir EMUI-Icons
          cp -r ./MIUI-Adapted-Icons-Complement-Project/icons ./EMUI-Icons/icons
          cd ./EMUI-Icons/icons
          flist=$(ls)
          for f in $flist
          do
            if test -d ./$f
            then
              cd $f
              convert 0.png -gravity center -crop 93.75%x93.75%+0+0 background.png
              rm 0.png
              convert 1.png -gravity center -crop 93.75%x93.75%+0+0 foreground.png
              rm 1.png
            fi
          done
          cd ../../

      - name: Pack
        run: |
          zip -r icons.zip EMUI-Icons

      - name: Upload articact
        uses: actions/upload-artifact@v2
        with:
          path: |
            icons.zip
          name: icons
