name: update-emui-icons
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: mfinelli/setup-imagemagick@v1

      - name: Get ImageMagick version
        run: |
          convert -version

      - name: Clone MIUI Icons
        run: |
          git clone https://github.com/pzcn/MIUI-Adapted-Icons-Complement-Project.git

      - name: Change directory
        run: |
          mkdir EMUI-Icons
          cp -r ./MIUI-Adapted-Icons-Complement-Project/icons ./EMUI-Icons/icons
          cd ./EMUI-Icons/icons
          mv ${GITHUB_WORKPLACE}/.github/rename.sh ./rename.sh
          chmod 755 ./rename.sh
          sh ./rename.sh
          cd ${GITHUB_WORKPLACE}

      - name: Pack
        run: |
          zip -r icons.zip EMUI-Icons

      - name: Upload articact
        uses: actions/upload-artifact@v2
        with:
          path: |
            icons.zip
          name: icons
