name: update-emui-icons
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: mfinelli/setup-imagemagick@v1

      - name: Get ImageMagick Version
        run: |
          convert -version
